# Generated by Django 4.1.7 on 2023-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_horrordb_delete_horror'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('page', models.PositiveIntegerField()),
                ('side', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
