# Generated by Django 4.1.7 on 2023-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0004_pompletdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='instaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('igid', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
