# Generated by Django 4.1.7 on 2023-05-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0005_instadb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instadb',
            old_name='igid',
            new_name='ig',
        ),
    ]
